[project]
name = "neuraloperator"
version = "0.3.0"
description = "NeuralOperator: Learning in Infinite Dimensions"
authors = [
    {name = "Jean Kossaifi <jean.kossaifi@gmail.com>, David Pitt <david.h.pitt@gmail.com>, Nik Kovachki, Zongyi Li", email="david.h.pitt@gmail.com"},
]
dependencies = [
    "wandb",
    "ruamel-yaml",
    "configmypy",
    "tensorly",
    "tensorly-torch",
    "torch-harmonics",
    "matplotlib",
    "opt-einsum",
    "h5py",
    "zarr",
]
requires-python = ">=3.9"
readme = "README.rst"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "pytest",
    "flaky",
    "black"
]
docs = [
    "matplotlib",
    "myst-nb",
    "numpydoc",
    "sphinx",
    "sphinx-gallery",
    "tensorly_sphinx_theme",
    "torchtnt",
]
all = [
    "pytest",
    "flaky",
    "black",
    "matplotlib",
    "myst-nb",
    "numpydoc",
    "sphinx",
    "sphinx-gallery",
    "tensorly_sphinx_theme",
    "torchtnt",
    "pytorch",
    "torchvision",
    "numpy",
    "scipy",
]



[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
